#!/usr/bin/bash

# Customize the command prompt

# powerline-shell/status both installed with pip
function _ps1_powerline() {
    export PS1=$(powerline-shell $?)
}
export _ps1_powerline

# in case powerline is not found
function _ps1_backup() {
    export PS1="\[\e[35m\][\[\e[m\]\[\e[35m\]\A\[\e[m\]\[\e[35m\]]\[\e[m\]\[\e[35m\] \[\e[m\]\[\e[35m\]\W\[\e[m\]\[\e[35m\] \[\e[m\]\[\e[35m\]\\$\[\e[m\] "
}
export _ps1_backup

if [[ # Conditions to use powerline-shell:
    $TERM != linux &&   # the type of terminal cannot be one without GUI
    `pip list` == *"powerline-shell"* &&    # the python module powerline-shell is found
    -f `which powerline-shell` ]]; then     # the shell command powerline-shell is found

    # echo "powerline-shell APPROVED"
    if [[ $PROMPT_COMMAND != *_ps1_powerline* ]]; then  # if powerline-shell is not in prompt
        export PROMPT_COMMAND="_ps1_powerline; $PROMPT_COMMAND"
        # echo "powerline-shell just added to prompt"
    # else
        # echo "powerline-shell already in prompt"
    fi
else
    # echo "powerline-shell REJECTED"
    if [[ $PROMPT_COMMAND == *_ps1_powerline* ]]; then  # if powerline-shell is already part of prompt
        export PROMPT_COMMAND= `sed -i "s/_ps1_powerline;//" $PROMPT_COMMAND`
        # echo "powerline-shell removed from prompt"
    fi
    _ps1_backup
fi
