#!/usr/bin/zsh

# Aliases

# Aliases are used as abbreviations and shorthands for commands that are used often.
# They are stored in the memory of the shell when they are created or sourced.
# If an alias is the same as a command, use "\" to use the original command.
# To make aliases available to shell scripts, use the command: 'shopt -s expand_aliases'

# Also, strings in single quotes are literal and do not interprete anything
# Strings with double quotes interpret variables and special characters ($, \, `)

# FLAGS (ZSH only)
# -g    Global: makes the alias usable at ANY point in the command
# -s    Suffix: sets preferred programs to open file extensions

# quick tools
alias -g grep='grep --color=auto'
alias rm='rm -i'
alias rmy='\rm -v'
alias mv='mv -v'
alias mkdir='mkdir -vp'
alias cp='cp -v'
alias c='clear'
alias pls='sudo $(fc -ln -1)'
alias diff='nvim -d'
alias less='less -N'

# History
alias h='history -E -50'
alias hg='history -E 1 | grep'
alias hf='history -E 1 | less +G' #full history

# ls
alias l='lsd -h'
alias ls='lsd -h'
alias la='lsd -Ah'
alias ll='lsd -AlFh'
alias lr='lsd -AlFhR'
alias lt='lsd -AlFht'

# navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# chmod
alias chmod='chmod -v'

# chezmoi aliases
alias cz='chezmoi'
alias czs='chezmoi status'
alias cza='chezmoi add'
alias czm='chezmoi managed'
alias czg='chezmoi git'
alias czd='chezmoi diff'
alias czcd='chezmoi cd'

# programs
alias -g vim='nvim'
alias -g vi='nvim'
alias -g v='nvim'
alias neo='neofetch'
alias cmatrix='cmatrix -ab -u 4 -C magenta'

# Find my Public IP Address
alias myip='curl http://ipecho.net/plain; echo'
