#!/usr/bin/zsh

# Anaconda Environment Integration

__conda_path="$HOME/.anaconda3/bin/conda"
__conda_setup="$($__conda_path 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME.anaconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME.anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/.anaconda3/bin:$PATH"
    fi
fi

conda config --set auto_activate_base False