#!/usr/bin/bash

# Aliases

# Aliases are used as abbreviations and shorthands for commands that are used often.
# They are stored in the memory of the shell when they are created or sourced.
# If an alias is the same as a command, use "\" to use the original command.
# To make aliases available to shell scripts, use the command: 'shopt -s expand_aliases'

# Also, strings in single quotes are literal and do not interprete anything
# Strings with double quotes interpret variables and special characters ($, \, `)

# quick tools
alias grep='grep --color=auto'
alias rm='rm -i'
alias rmy='\rm -v'
alias mv='mv -v'
alias mkdir='mkdir -vp'
alias cp='cp -v'
alias c='clear'
alias pls='sudo $(fc -ln -1)'
alias less='less -N'
alias chmod='chmod -v'

# navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# History
alias h='history'
alias hg='history | grep'
alias hf="cat $HOME/.bash_history | less +G" #full history

# chezmoi aliases
alias cz='chezmoi'
alias czs='chezmoi status'
alias cza='chezmoi add'
alias czra='chezmoi re-add'
alias czm='chezmoi managed'
alias czg='chezmoi git'
alias czd='chezmoi diff'
alias czcd='chezmoi cd'

# programs
if command -v lsd &> /dev/null; then
    alias l='lsd -h'
    alias ls='lsd -h'
    alias la='lsd -Ah'
    alias ll='lsd -AlFh'
    alias lr='lsd -AlFhR'
    alias lt='lsd -AlFht'
else
    alias l='ls -h'
    alias ls='ls -h'
    alias la='ls -Ah'
    alias ll='ls -AlFh'
    alias lr='ls -AlFhR'
    alias lt='ls -AlFht'
fi
if command -v nvim &> /dev/null; then
alias vim='nvim'
alias vi='nvim'
alias v='nvim'
alias diff='nvim -d'
fi
if command -v neofetch &> /dev/null; then
alias neo='neofetch'
fi
if command -v cmatrix &> /dev/null; then
alias cmatrix='cmatrix -ab -u 4 -C green'
fi
if command -v distrobox &> /dev/null; then
alias db='distrobox'
fi
alias joplin-sync-unlock='\rm -f Documents/Dropbox/Apps/Joplin/locks/*'

# Find my Public IP Address
alias myip='curl http://ipecho.net/plain; echo'

# Enter Distroboxes
alias main='distrobox enter MainBox'
