#!/usr/bin/bash

# Aliases

# Aliases are used as abbreviations and shorthands for commands that are used often.
# They are stored in the memory of the shell when they are created or sourced.
# If an alias is the same as a command, use "\" to use the original command.
# To make aliases available to shell scripts, use the command: 'shopt -s expand_aliases'

# Also, strings in single quotes are literal and do not interprete anything
# Strings with double quotes interpret variables and special characters ($, \, `)

# quick tools
alias grep='grep --color=auto'
alias rm='rm -i'
alias rmy='\rm -v'
alias mv='mv -v'
alias mkdir='mkdir -vp'
alias cp='cp -v'
alias c='clear'
alias pls='sudo $(fc -ln -1)'
alias less='less -N'
alias diff='nvim -d'

# History
alias h='history'
alias hg='history | grep'
alias hf="cat $HOME/.bash_history | less +G" #full history

# ls
alias l='lsd -h'
alias ls='lsd -h'
alias la='lsd -Ah'
alias ll='lsd -AlFh'
alias lr='lsd -AlFhR'
alias lt='lsd -AlFht'

# navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# package manager
alias dnfs='dnf search'
alias dnfg='dnf list installed | grep'
alias update='sudo dnf update'
alias updatey='sudo dnf update -y'
alias updateall='sudo dnf update -y && flatpak update -y'

# git
alias gdone='git push'
alias gs='git status -sb'

# chmod
alias chmod='chmod -v'

# chezmoi aliases
alias cz='chezmoi'
alias czs='chezmoi status'
alias cza='chezmoi re-add; echo "added local changes to chezmoi VCS"'
alias czm='chezmoi managed'
alias czg='chezmoi git'
alias czd='chezmoi diff'
alias czcd='chezmoi cd'

# programs
alias vim='nvim'
alias vi='nvim'
alias v='nvim'
alias neo='neofetch'
alias cmatrix='cmatrix -ab -u 4 -C magenta'
alias df='pydf'
alias top='bpytop'

# Programs Configuration
alias zsh_config="cd $ZDOTDIR"
alias kitty_config="$EDITOR $XDG_CONFIG_HOME/kitty/kitty.conf"
alias neofetch_config="$EDITOR $XDG_CONFIG_HOME/neofetch"
alias vi_config="$EDITOR $XDG_CONFIG_HOME/nvim/init.vim"

# Find my Public IP Address
alias myip='curl http://ipecho.net/plain; echo'
