#!/usr/bin/bash

# Customize the command prompt (https://ezprompt.net/) and colors (https://misc.flogisoft.com/bash/tip_colors_and_formatting)

export PS1="\[\e[32m\][\[\e[m\]\[\e[35m\]\w\[\e[m\]
\[\e[33m\][\t]\[\e[m\] \[\e[35m\]\u\[\e[33m\]@\[\e[35m\]\h\[\e[m\] \`if [ \$? = 0 ]; then echo \[\e[33m\]\$\[\e[m\]; else echo \[\e[31m\]\$\[\e[m\]; fi\` "
