#!/usr/bin/bash

# Customize the command prompt

# powerline-shell/status both installed with pip
function _ps1_powerline() {
    export PS1=$(powerline-shell $?)
}
export _ps1_powerline

# in case powerline is not found
function _ps1_backup() {
    export PS1="\[\e[35m\][\[\e[m\]\[\e[35m\]\A\[\e[m\]\[\e[35m\]]\[\e[m\]\[\e[35m\] \[\e[m\]\[\e[35m\]\W\[\e[m\]\[\e[35m\] \[\e[m\]\[\e[35m\]\\$\[\e[m\] "
}
export _ps1_backup

if [[ # Conditions to use powerline-shell:
    $TERM != linux &&   # if the type of terminal has a GUI
    `pip list` == *"powerline-shell"* &&    # and the python module powerline-shell is found
    -f `which powerline-shell` ]]; then     # and the shell command powerline-shell is found

    # powerline-shell is available; add it to the prompt command if not already
    if [[ $PROMPT_COMMAND != *_ps1_powerline* ]]; then
        export PROMPT_COMMAND="_ps1_powerline; $PROMPT_COMMAND"
    fi

else
    # powerline-shell is not available; remove it from the prompt command if it is there
    if [[ $PROMPT_COMMAND == *_ps1_powerline* ]]; then
        export PROMPT_COMMAND= `sed -i "s/_ps1_powerline;//" $PROMPT_COMMAND`
        # echo "powerline-shell removed from prompt"
    fi
    # set the alternative prompt
    _ps1_backup
fi
