#!/usr/bin/bash

# Functions can be more rich and complex than aliases.
# They can contain multiple lines of instructions and loops.
# Like aliases, they are stored in memory after being sourced from a file or declared.
# However, they can be exported to be used by scripts.

# Shell scripts run in forked non-interactive shells.
# A script should be independent of the environment and should stand on its own.

# Because gnome-terminal is hardcoded as the default terminal, I use a shortcut to swap it.
change_terminal() {
    # Open a new terminal while indicating the current directory
    $1 --working-directory="$PWD" &

    # Make the new process independent
    disown

    # Exit the current terminal
    pkill gnome-terminal
}

alias ct="change_terminal kitty"

# Replace the osu application with the updated version and fix the menu entry in one command.
osu-update() {
    echo "Closing current osu! session..."
    pkill osu\!

    echo "Moving the up-to-date osu!lazer AppImage to the Applications folder..."
    \mv -v $HOME/Downloads/osu.AppImage $HOME/Applications/osuLazer.AppImage

    echo "Making the file executable..."
    chmod -v 755 $HOME/Applications/osuLazer.AppImage

    echo "Launching osu!lazer..."
    $HOME/Applications/osuLazer.AppImage 2> /dev/null &

    # Make the new process independent
    disown

    # Exit the terminal
    exit
}
