#!/bin/zsh

# The first zsh config file to be read.
# Used to set environment variables.

# This file is placed in the home directory and only used to set ZDOTDIR.
# To set more environment variables, go to '$HOME/.config/zsh/.zshenv'.

# Setting the directory for ZSH config files
ZDOTDIR=$HOME/.config/zsh
# Run the 'main .zshenv' in the zsh folder
. $ZDOTDIR/.zshenv
