#!/usr/bin/zsh

# Because gnome-terminal is hardcoded as the default terminal, I use a shortcut to swap it.

# Find the name of the current terminal
    currentTerminal=$(< "/proc/${1:-$PPID}/comm")

change_terminal() {
    # Open a new terminal while indicating the current directory
    $1 --working-directory="$PWD" &

    # Make the new process independent
    disown

    # Kill the current terminal emulator process (Kills ALL instances)
    pkill $currentTerminal
}
alias ct="change_terminal kitty"
