#!/usr/bin/zsh

# Replace the osu application with the updated version and fix the menu entry in one command.
osu-update() {
    echo "Closing current osu! session..."
    pkill osu\!

    echo "Moving the up-to-date osu!lazer AppImage to the Applications folder..."
    \mv -v $HOME/Downloads/osu.AppImage $HOME/Applications/osuLazer.AppImage

    echo "Making the file executable..."
    chmod -v u+x $HOME/Applications/osuLazer.AppImage

    echo "Launching osu!lazer..."
    $HOME/Applications/osuLazer.AppImage 2> /dev/null &

    # Make the new process independent
    disown

    # Exit the terminal
    exit
}
