#!/usr/bin/zsh

# Custom Functions

# Functions can be more rich and complex than aliases.
# They can contain multiple lines of instructions and loops.
# Like aliases, they are stored in memory after being sourced from a file or declared.
# However, they can be exported to be used by scripts.

# Shell scripts run in forked non-interactive shells.
# A script should be independent of the environment and should stand on its own.
