#!/usr/bin/zsh

# Because gnome-terminal is hardcoded as the default terminal, I use this workaround
# to open the terminal I want in the same directory, then close gnome-terminal.

# Add a favorite terminal emulator
favoriteTerminal=kitty

# Find the name of the current terminal
currentTerminal=$(< "/proc/${1:-$PPID}/comm")

# Switch on/off
swapGnomeTerminal=True

# If the current parent process (which should correcpond to the terminal emulator) is gnome-terminal
if [[ $currentTerminal = "gnome-terminal-" && $swapGnomeTerminal = True ]]; then
	# Open a new terminal while indicating the current directory
    $favoriteTerminal --working-directory="$PWD" &

    # Make the new process independent
    disown

    # in case gnome-terminal wasn't stopped, print the process that was caught instead
    echo $currentTerminal

    # Kill the current terminal emulator process (Kills ALL instances)
    pkill $currentTerminal
fi

unset favoriteTerminal
unset currentTerminal