#!/usr/bin/zsh

# The first zsh config file to be read.
# Used to set environment variables.
# Variables set here are available everywhere, including scripts

if ! [[ "$PATH" =~ "$HOME/.local/bin:" ]]
then
    export PATH="$HOME/.local/bin:$PATH"
fi


export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export EDITOR=nvim
export VISUAL=nvim