#!/usr/bin/zsh

# The first zsh config file to be read.
# Used to set environment variables.
# Variables set here are available everywhere, including scripts

# This script should not produce any output or assume the shell is attached to a TTY

# Language and locale
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Editor
export EDITOR=nvim
export VISUAL=nvim

# Default Folders
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="$HOME/.config"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:="$HOME/.cache"}
export XDG_DATA_HOME=${XDG_DATA_HOME:="$HOME/.local/share"}
export XDG_STATE_HOME=${XDG_STATE_HOME:="$HOME/.local/state"}

# Pager to display file content in terminal
export PAGER='less -R'      #less with color interpretation ad output

# Disable less history
export LESSHISTFILE=-

# Web Browser
export BROWSER="firefox"

# Add to PATH
if ! [[ "$PATH" =~ "$HOME/.local/bin:" ]]
then
    export PATH="$HOME/.local/bin:$PATH"
fi
