#!/usr/bin/zsh

# Script launched at login

# It does basically the same thing as 'zprofile' except that
# zlogin is derived is a derivative of CSH's .login whereas
# zprofile is a derivative of bash's .bash_profile.

# Let's stick with zprofile since .bash_profile is more familiar.